# This file lists tools managed by Rokit/aftman, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

# Rojo doesn't work even rokit installed it.

[tools]
selene = "kampfkarren/selene@0.29.0"
rojo = "rojo-rbx/rojo@7.5.1"
StyLua = "JohnnyMorganz/StyLua@2.0.2"