name: Feature Request
description: Suggest a idea.
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: input_feature
    attributes:
      label: Suggest your Feature at here
      placeholder: any...
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: Related Links
      placeholder: You can set any related links at here.
    validations:
      required: false