# THIS IS GENERATE BY AI, JUST FOR TEST

name: 💡 Feature Request
description: Suggest an idea
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true