name: Feature Request
description: Suggest a idea.
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: input_feature
    attributes:
      label: Suggest your Feature at here
      placeholder: any...
      value: "I have a very cool idea to suggest!"
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: Related Contents
      placeholder: You can set any related contents at here.
      value: "Related Content"
    validations:
      required: false