# THIS IS GENERATE BY AI, JUST FOR TEST

name: 💡 Feature Request
description: Suggests a idea of feature or anything else!
title: "Issue Title here"
labels: ["enhancement"]
body:
  - type: markdown
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true